---
title: "exploratory analysis using data summaries"
output: pdf_document
date: "2023-10-05"
---

```{r}
library(tidyverse)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())


weather_df
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())
```

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) +
  geom_histogram()
```


```{r}
weather_df |> 
  filter(prcp > 1000)
```


```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point()
```

```{r}
weather_df |> 
  group_by(name)
```

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize()
```

```{r}
weather_df |> 
  group_by(month) |> 
  summarize(nobs = n())
```

```{r}
weather_df |> 
  count(name, name = "n_obs")
```

```{r}
weather_df |> 
  count(name, month)
```

```{r}
weather_df |> 
  count(name, month) |> 
  pivot_wider(
    names_form = name,
    values_from = n
  )
```

```{r}
weather_df |> 
  group_by(name) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = FALSE)
  )
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |>
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + 
    geom_line() + 
    theme(legend.position = "bottom")
```


```{r}
weather_df |>
  group_by(name, month) |>
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |> 
  knitr::kable()
```

## grouped mutate

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) |> 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_bin_2d() +
  geom_point() +
  geom_abline() +
  geom_violin() +
  geom_area() +
  geom_blank() +
  geom_col() +
  geom_count() +
  geom_jitter() +
  geom_line()

```

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(yesterday_tmax = lag(tmax))
```

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(temp_change = tmax - lag(tmax)) |> 
  summarize(
    sd_temp_change = sd(temp_change, na.rm = TRUE)
  )
```









